apiVersion: apps/v1
kind: Deployment
metadata:
  name: image-deployment
  labels:
    app: my-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: my-app
        image:  252820710416.dkr.ecr.ap-northeast-1.amazonaws.com/latesh:latest
        ports:
        - containerPort: 9099