apiVersion: v1
kind: Service
metadata:
  name: my-app
spec:
  selector:
    app: my-app
  type: LoadBalancer
  ports:
  - name: my-app
    protocol: TCP
    port: 80
    targetPort: 9099
    nodePort: 30035